#!/bin/bash
#SBATCH --job-name=zoarcoidei_hifiasm
#SBATCH --partition=128x24
#SBATCH --output=out/hifiasm_onlyhifi_species_%A_%a.out
#SBATCH --error=err/hifiasm_onlyhifi_species_%A_%a.err
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=2
#SBATCH --cpus-per-task=4
#SBATCH --mem=120GB
#SBATCH --time=5-00:00:00

# Move directories
cd /path/to/species/fastq.gz/data

# Load dependencies
module load miniconda3

conda activate hifiasm

# hifi reads only
hifiasm -o species_hifi.asm -t20 file_A_hifi.fastq.gz file_B_hifi.fastq.gz
2> species_hifi.asm.log
