#!/bin/bash
#SBATCH --job-name=zoarcoidei_hifiasm
#SBATCH --mail-user=omoosman@ucsc.edu
#SBATCH --mail-type=ALL
#SBATCH --output=/hb/home/omoosman/owen/zoarcoidei/data/err_out/hifiasm_onlyhifi_%A_%a.out
#SBATCH --error=/hb/home/omoosman/owen/zoarcoidei/data/err_out/hifiasm_onlyhifi_%A_%a.err
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=20
#SBATCH --mem=100GB
#SBATCH --time=5-00:00:00

# Load dependencies
module load miniconda3
conda activate hifiasm

#defining species name and path to fastq.gz
config_file=/hb/groups/kelley_training/owen/zoarcoidei/data/sra_id.txt
name=$(sed -n "${SLURM_ARRAY_TASK_ID}p" "$config_file" | awk '{print $2}')
file=$(ls /hb/groups/kelley_training/owen/zoarcoidei/data/raw_hifi/$name/*.fastq.gz)

# Make out directory and move to directory with input files
mkdir -p /hb/home/omoosman/owen/zoarcoidei/data/assemblies/$name
cd /hb/groups/kelley_training/owen/zoarcoidei/data/raw_hifi/$name

# hifi reads only
hifiasm -o /hb/home/omoosman/owen/zoarcoidei/data/assemblies/$name/"${name}_hifi.asm" -t20 "$file" 2> /hb/home/omoosman/owen/zoarcoidei/data/assemblies/$name/"${name}_hifi.asm.log"


file_numb=$(ls /hb/groups/kelley_training/owen/zoarcoidei/data/raw_hifi/$name/*.fastq.gz | wc -l)

if [[ $file_num -eq 1 ]]; then
  echo "there is one file"
else
  echo "there are two files"
fi
