#!/bin/bash
#SBATCH --job-name=pbmm2_align
#SBATCH --mail-user=omoosman@ucsc.edu
#SBATCH --mail-type=ALL
#SBATCH --output=/hb/home/omoosman/owen/zoarcoidei/data/err_out/align/align_%A_%a.out
#SBATCH --error=/hb/home/omoosman/owen/zoarcoidei/data/err_out/align/align_%A_%a.err
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=20
#SBATCH --mem=100GB
#SBATCH --time=5-00:00:00

# Load dependencies
module load miniconda3
conda activate pbmm2

#alignment
pbmm2 align ref.fa in.fa out.bam --preset HIFI


--sort

--rg '@RG\tID:myid\tSM:mysample
