#!/bin/bash
#SBATCH --job-name=SRA_accession
#SBATCH --time=0-12:00:00 # Wall clock time limit in Days-Hours:min:seconds
#SBATCH --output=SRA-%A_%a.out # output file
#SBATCH --error=SRA-%A_%a.err # error file
#SBATCH --ntasks=1 # Run 1 job
#SBATCH --ntasks-per-node=1 
#SBATCH --cpus-per-task=8 
#SBATCH --mem=100GB

module load sratoolkit

fasterq-dump SRRXXXXXXXXXX -t /hb/scratch/omoosman/SRA -O /hb/home/omoosman/owen/zoarcoidei/data/raw_hifi && gzip /hb/home/omoosman/owen/zoarcoidei/data/raw_hifi/SRRXXXXXXXXXX/*.fastq  
