---
title: "haplo_afp"
output: html_document
date: "2024-11-27"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)


library(tidyverse)
library(ggtree)
library(ape)
library(phytools)
library(readxl)
library(aplot)
library(cowplot)
library(fishtree)
library(brms)

```

```{r}
#fig s1

#import data

haplo_afp <- read_excel("C:/Users/omoos/Downloads/zoarcoidei_haplo-afp (17).xlsx", sheet = "fig_6")

# For SB -
# haplo_afp <- read.csv("~/Documents/GitHub/haplo_afp/figure_code/zoarcoidei_haplo-afp - fig_6.csv")

#data manipulation

haplo_afp$margin <- (haplo_afp$max - haplo_afp$min)
haplo_afp$perc_uncert <- (haplo_afp$margin / haplo_afp$max)

error_median <- ggplot(haplo_afp, aes(x = median, y = perc_uncert)) +
  stat_smooth(method = "glm", method.args = list(family = "binomial"),
              se = TRUE, col = "blue") +
                geom_point(size=2.5) +
                scale_y_continuous(breaks = seq(0, 0.6, by = 0.1)) +
                scale_x_continuous(breaks = seq(0, 100, by = 10)) +
                labs(y = "Percent uncertainty", x = "Median copy number per AFP array") +
                coord_cartesian(ylim = c(0, 0.6)) +
                theme_classic(base_size = 20)

error_median

# Fit zero inflated beta model
error_brm <- brm(
  perc_uncert ~ median, 
  data = haplo_afp,
  family = zero_inflated_beta(),
  chains = 4, iter = 40000,
  save_pars = save_pars(all = TRUE)
)

summary(error_brm)

plot(error_brm)

conditional_effects(error_brm)



```


```{r}
#fig5 tree
hap_afp_tree <- fishtree_phylogeny(
  c("Lycodichthys dearborni", "Zoarces americanus", "Leptoclinus maculatus",
    "Pholis gunnellus", "Cebidichthys violaceus", "Anarhichas minor", "Anarhichas lupus"),
  type = c("chronogram"))

# Get the root age (total tree height)
tree_age <- max(ggtree(hap_afp_tree)$data$x)

# Format species names
hap_afp_tree$tip.label <- gsub("_", " ", hap_afp_tree$tip.label)
hap_afp_tree$tip.label <- paste0("italic('", hap_afp_tree$tip.label, "')")

# Plot tree to see if it looks accurate
tree_panel <- ggtree(hap_afp_tree) + 
  geom_tiplab(fontface = "italic", parse = TRUE, size = 5) + 
  theme_tree2() +
  geom_tree(size = 1) +
  labs(x = "Mya") +
  theme(
    axis.title.x = element_text(size = 20),
    axis.text.x = element_text(size = 15)) +
  scale_x_continuous(
    limits = c(-2, tree_age + 35),  # Extends left for labels, ends at 0
    breaks = tree_age - c(40, 30, 20, 10, 0),  
    labels = c(40, 30, 20, 10, 0),
    expand = c(0, 0)  # Ensures axis line ends at 0 without extra space
  )
tree_panel
```

```{r}
##fig5 dotplot

#import data

haplo_afp <- read.csv("~/Documents/GitHub/haplo_afp/zoarcoidei_haplo-afp - fig_6.csv")

#order species by their appearance in the data set rather than alphabetically

haplo_afp$species <- factor(haplo_afp$species, levels = unique(haplo_afp$species))

#change NA to "" in order to remove NA label in legend
haplo_afp$haplotype <- as.character(haplo_afp$haplotype)  # Convert to character
haplo_afp$haplotype[is.na(haplo_afp$haplotype)] <- ""  # Replace NA with empty string
haplo_afp$haplotype <- factor(haplo_afp$haplotype)  # Convert back to factor

# plot
dotplot <- ggplot(haplo_afp, aes(
                              x = median,
                              y = interaction(array, species), 
                              colour = haplotype)) +
  geom_point(position = position_dodge(width = 0.8), size = 3) +
  geom_errorbar(aes(
                xmin = min, xmax = max), 
                width = 0, 
                size = 1, 
                position = position_dodge(width = 0.8, preserve = "total")) +
  scale_x_continuous(breaks = seq(0, 130, by = 20)) +
  scale_y_discrete(limits = rev) +
  labs(y = "", x = "AFP copy number", color = "Haplotype") +
  scale_color_manual(values = c("hap1" = "#D71920", "hap2" = "#5BCBF5", "Unresolved" = "black")) +
  
  # Add group labels
  geom_text(aes(x = -20, label = array), hjust = 0.25, size = 5, color = "black") +

  # Use facets to separate species but remove labels
  facet_wrap(~ species, scales = "free_y", ncol = 1) +

  # adjust theme
  theme_classic(base_size = 20) +
  theme(strip.text = element_blank(),  # Remove facet labels
        panel.spacing = unit(0.5, "lines"),  # Increase spacing between species
        axis.text.y = element_blank(),  # Remove y-axis text
        axis.ticks.y = element_blank(),  # Remove y-axis ticks
        legend.position = "inside",
        legend.position.inside = c(0.8,0.8),
        plot.margin = margin(5, 10, 5, 0))

#combine plots

fig5 <- cowplot::plot_grid(tree_panel, dotplot, rel_widths = c(1,1.5))

fig5

ggsave(fig5,
       units = "in", width = 12, height = 6, 
       filename = "~/Documents/GitHub/haplo_afp/fig6.png",
       bg = "white")

##export size is 1400x900##
```
